- examples/web-browser.html
- package.json
- src/_index.node.ts
- src/_index.web.ts
- src/serialize/XmlSerializer.web.ts
- src/serialize/_index.node.ts
- src/serialize/_index.web.ts
- src/serialize/index.ts
- tsconfig.node.json
- tsconfig.web.json
- webpack.config.js
just one option to split the builds by target.
alternative to #40
> Targetized split `module/module`

- src/serialize/baseSerializer.ts
this allowes the use of the AbstractBaseClass as it was an Interface.
Only the implementations actually care for the `NormalizedBom` - which is ily used internally in protected functions ,,,,.
example usage
```javascript
function f (serializer: BaseSerializer, bom: Bom): any {
return { source: () => serializer.serialize(bom, serializeOptions) }
}
```
instead of 
```javascript
function f (serializer: BaseSerializer<any>, bom: Bom): any {
return { source: () => serializer.serialize(bom, serializeOptions) }
}
```
> `BaseSerializer`'s TemplateType `NormalizedBom` defaults to `any` now.

- src/helpers/sortableSet.ts
- src/models/component.ts
- src/models/externalReference.ts
- src/models/tool.ts
purpose: make the implementation and the purpose of `compare` clearer
> docs: add comment to the `compare` methods

- HISTORY.md
- src/types/cpe.ts
- tests/unit/Types/cpe.spec.js
> fix: `Types.isCPE()` CPE2.3 with escaped chars `&"><` are allowed

- HISTORY.md
- src/serialize/json/normalize.ts
- src/serialize/xml/normalize.ts
- src/spec.ts
- tests/_data/normalizeResults/json_sortedLists_spec1.4.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
- tests/_data/serializeResults/json_complex_spec1.4.json.bin
- tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
CycloneDX spec version 1.4 made element `bom.component.version` optional.  
Therefore, serialization/normalization with this spec version will no longer render this element, when its value is empty.
> spec1.4: omit empty `component.version`

- HISTORY.md
- src/helpers/tree.ts
- src/models/component.ts
- src/serialize/json/normalize.ts
- src/serialize/xml/normalize.ts
- tests/_data/models.js
- tests/_data/normalizeResults/json_sortedLists_spec1.2.json
- tests/_data/normalizeResults/json_sortedLists_spec1.3.json
- tests/_data/normalizeResults/json_sortedLists_spec1.4.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
- tests/_data/serializeResults/json_complex_spec1.2.json.bin
- tests/_data/serializeResults/json_complex_spec1.3.json.bin
- tests/_data/serializeResults/json_complex_spec1.4.json.bin
- tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
- tests/integration/Serialize.JsonNormalize.test.js
- tests/integration/Serialize.JsonSerialize.test.js
- tests/integration/Serialize.XmlNormalize.test.js
- tests/integration/Serialize.XmlSerialize.test.js
- tests/unit/Models.Component.spec.js
part of  #132
* Support for nested/bundled (sub-)components via `Models.Component.components` was added, including
serialization/normalization of models and impact on dependency graphs rendering.
* data models  for `Models.Component.components` - its another instance of `Models.ComponentRepository`
* implement normalizer for `Models.Component.components`
* implement dependency tree for `Models.Component.components`
> add support for sub-components (`Models.Component.components`)

- HISTORY.md
- src/builders/fromPackageJson.node.ts
- src/factories/packageUrl.ts
- src/serialize/bomRefDiscriminator.ts
- src/serialize/json/normalize.ts
- src/serialize/jsonSerializer.ts
- src/serialize/xml/normalize.ts
- src/serialize/xmlBaseSerializer.ts
- tests/unit/Builders.FromPackageJson.ComponentBuilder.spec.js
- tests/unit/Builders.FromPackageJson.ToolBuilder.spec.js
- tests/unit/Factories.PackageUrlFactory.spec.js
- tests/unit/Serialize.BomRefDiscriminator.spec.js
- tests/unit/Serialize.JsonSerializer.spec.js
- tests/unit/Serialize.XmlBaseSerializer.spec.js
- tests/unit/Serialize.XmlSerializer.spec.js
- tests/unit/Types.cpe.spec.js
* Getters/properties that represent the corresponding parameters of class constructor.
* `Builders.FromPackageJson.ComponentBuilder.extRefFactory`,  
`Builders.FromPackageJson.ComponentBuilder.licenseFactory`
* `Builders.FromPackageJson.ToolBuilder.extRefFactory`
* `Factories.PackageUrlFactory.type`
* `Serialize.BomRefDiscriminator.prefix`
* `Serialize.JsonSerializer.normalizerFactory`
* `Serialize.XmlBaseSerializer.normalizerFactory`,  
`Serialize.XmlSerializer.normalizerFactory`
> add getters for construtor parameters

- HISTORY.md
- package.json
- src/factories/packageUrl.ts
- tests/README.md
- tests/integration/Factories.PackageUrlFactory.test.js
* Factory for `PackageURL` from `Models.Component` can handle additional data sources, now.
* `Models.Component.hashes` map -> `PackageURL.qualifiers.checksum` list
* `Models.Component.externalReferences[distribution].url` -> `PackageURL.qualifiers.download_url`
* Method `Factories.PackageUrlFactory.makeFromComponent()` got a new optional param `sort`,
to indicate whether to go the extra mile and bring hashes and qualifiers in alphabetical order.  
This feature switch is related to reproducible builds.
----
> `PackageUrlFactory::makeFromComponent()` - `checksums` and `download_url`

- HISTORY.md
- src/serialize/json/normalize.ts
- src/serialize/xml/normalize.ts
- src/spec.ts
- tests/_data/normalizeResults/json_sortedLists_spec1.2.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
- tests/_data/serializeResults/json_complex_spec1.2.json.bin
- tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
* Fixed
* JSON- and XML-Normalizer no longer render `Models.Component.properties` with [_CycloneDX_ Specification][CycloneDX-specification]-1.2. ([#152] via [#153])
* XML-Normalizer now has the correct order/position of rendered `Models.Component.properties`. (via [#153])
[#152]: https://github.com/CycloneDX/cyclonedx-javascript-library/issues/152
[#153]: https://github.com/CycloneDX/cyclonedx-javascript-library/pull/153
[CycloneDX-specification]: https://github.com/CycloneDX/specification/tree/main/schema
> fix normalixer of `Models.Component.properties` with CDX-1.2

- HISTORY.md
- src/serialize/baseSerializer.ts
- tests/integration/Serialize.JsonSerialize.test.js
- tests/integration/Serialize.XmlSerialize.test.js
> fix: `BaseSerializer` discriminate nested components

- HISTORY.md
- src/factories/packageUrl.ts
- tests/integration/Factories.PackageUrlFactory.test.js
`Factories.PackageUrlFactory` omits empty-string URLs for PackageUrl's qualifiers `download_url` & `vcs_url`.
just omit empty urls ... No further need for validation.
According to <https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst> there is no formal requirement to a `..._url`.
Everything is possible: URL-encoded, not encoded, with schema, without schema
> fix: PackageUrlFactory omit empty ext-ref urls

- HISTORY.md
- src/factories/fromNodePackageJson.node.ts
- src/factories/packageUrl.ts
- src/helpers/packageUrl.ts
- tests/integration/Factories.FromNodePackageJson.PackageUrlFactory.test.js
* New class `Factories.FromNodePackageJson.PackageUrlFactory` that acts like `Factories.PackageUrlFactory`, but
omits PackageUrl's npm-specific "default derived" qualifier values for `download_url` & `vcs_url`.
fixes #204
> feat: `Factories.FromNodePackageJson.PackageUrlFactory` to omits PURL's npm defaults

- src/resources.node.ts
- tsconfig.json
Enables projects that use this library to also have esModuleInterop set to false (which is the more strict options), improving ease of use.
> tsconfig: default `esModuleInterop` & `allowSyntheticDefaultImports`

- HISTORY.md
- README.md
- examples/README.md
- examples/node/example.cjs
- examples/node/example.mjs
- examples/web-browser.html
i researched downstream usage of this library,
and found some projects that did not use the dependency models right.
to prevent such cases in the future, examples were added, that showcase how dependencyies are intended to be modelled.
> add documentation and example regarding dependency tree modelling

- src/serialize/baseSerializer.ts
- src/serialize/types.ts
goal: make the `BaseSerializer` more readable and intuitive.
> docs: add more docs to serializer

- .eslintrc.js
- libs/universal-node-xml/stringifiers/helpers.js
- libs/universal-node-xml/stringifiers/xmlbuilder2.js
- package-lock.json
- package.json
- src/builders/fromNodePackageJson.node.ts
- src/factories/fromNodePackageJson.node.ts
- src/index.node.ts
- src/serialize/baseSerializer.ts
- src/spdx.ts
- src/spec.ts
- src/types/cpe.ts
- src/types/integer.ts
- src/types/urn.ts
- tests/_data/models.js
- tests/_data/normalize.js
- tests/_data/serialize.js
- tests/_data/specLoader.js
- tests/_helpers/stringFunctions.js
https://jsdoc.app/
see also #318
> assure valid jsdoc

- HISTORY.md
- src/models/attachment.ts
- src/models/bom.ts
- src/models/component.ts
- src/models/externalReference.ts
- src/models/license.ts
- src/models/metadata.ts
- src/models/organizationalContact.ts
- src/models/organizationalEntity.ts
- src/models/swid.ts
- src/models/tool.ts
fixes #439
- prefix all `OptionalProperties` with the target - ala `OptionalSpdxLicenseProperties`
- export them OptionalProperties
> feat: export optional properties of modules

- .eslintrc.js
- HISTORY.md
- examples/node-javascript/example.cjs
- examples/node-javascript/example.mjs
- package-lock.json
- package.json
- src/_helpers/packageJson.ts
- src/_helpers/packageUrl.ts
- src/builders/fromNodePackageJson.node.ts
- src/factories/fromNodePackageJson.node.ts
- src/factories/license.ts
- src/models/bom.ts
- src/models/component.ts
- src/models/license.ts
- src/models/swid.ts
- src/serialize/baseSerializer.ts
- src/serialize/json/types.ts
- src/serialize/jsonSerializer.ts
- src/serialize/types.ts
- src/serialize/xml/normalize.ts
- src/serialize/xml/types.ts
- src/serialize/xmlBaseSerializer.ts
- src/spdx.ts
- src/types/cpe.ts
- src/types/integer.ts
- src/types/mimeType.ts
- src/types/urn.ts
- tsdoc.json
* ship valid tsdoc - https://tsdoc.org 
* improved docs rendering for links and refs
on the long run i would prefer TSDoc is ts-files, and JsDoc in js files .... 
supports #57
OUTDATED: 
> unfortunatelty the IDEs I tested do not know TSDoc. they know JsDOC instead ... therefore: #319
> Hope this changes in the future. see https://youtrack.jetbrains.com/issue/WEB-36309/Integrate-TSDOC-to-webstorm
----
> docs: use TSDoc - instead of JSDoc

- README.md
`pnpm` finally got working support to install packages form GitHub and run the `prepublish` scripts, that are needed to compile the TypeScript of this package in install-time.
so let's document this.
> docs: describe how to install from source with `pnpm`

- README.md
yarn2 (`yarn init -2`) finally has working support to install from source and run all needed `prepublish` scripts in install-time.
let's document this.
> docs: describe how to install from source with `yarn2`

- .github/workflows/nodejs.yml
some tests keep on crashing ... https://github.com/CycloneDX/cyclonedx-javascript-library/actions/runs/4270034656/jobs/7433604150 
but these testst are not actually required ...
> ci: remove unnessessarry error-prone tests for type digest

- src/serialize/baseSerializer.ts
> feat: base-serializer runs bomRefDiscrimination on vulnerabilities

- HISTORY.md
- README.md
- src/models/attachment.ts
- src/models/component.ts
- src/serialize/json/normalize.ts
- src/serialize/json/types.ts
- src/serialize/xml/normalize.ts
- src/spec.ts
- tests/_data/models.js
- tests/_data/normalizeResults/json_sortedLists_spec1.2.json
- tests/_data/normalizeResults/json_sortedLists_spec1.3.json
- tests/_data/normalizeResults/json_sortedLists_spec1.4.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
- tests/_data/serializeResults/json_complex_spec1.2.json.bin
- tests/_data/serializeResults/json_complex_spec1.3.json.bin
- tests/_data/serializeResults/json_complex_spec1.4.json.bin
- tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
> models `ComponentEvidence`

- libs/universal-node-xml/stringifiers/xmlbuilder2.js
fixes
> Check warning on line 60 in libs/universal-node-xml/stringifiers/xmlbuilder2.js
GitHub Actions / test standard
> 
> Defaults are not permitted on @param. (jsdoc/no-defaults)
> docs: fix jsdoc warning from eslint foo

- HISTORY.md
- src/serialize/xml/normalize.ts
* Classes `Serialize.Xml.Normalize.Vulnerability*Normalizer` are now public available  
Previously, they were only available via `Serialize.Xml.Normalize.Factory.makeForVulnerability*()`.
> Xmlserializer public normalizers for vuln

- HISTORY.md
- examples/node/javascript/example.cjs
- examples/node/javascript/example.mjs
- examples/node/typescript/example.cjs/src/example.ts
- examples/node/typescript/example.mjs/src/example.ts
- examples/web/parcel/src/app.js
- examples/web/webpack/src/index.js
used `generic` PURLS, to make examples more ... generic,
and to circumvent confusion with `FromNodePackageJson.PackageUrlFactory`
> docs(examples): use `generic` packageurls

- HISTORY.md
- src/models/externalReference.ts
- src/serialize/json/normalize.ts
- src/serialize/json/types.ts
- src/serialize/xml/normalize.ts
- src/spec/_protocol.ts
- src/spec/consts.ts
- tests/_data/models.js
- tests/_data/normalizeResults/json_sortedLists_spec1.2.json
- tests/_data/normalizeResults/json_sortedLists_spec1.3.json
- tests/_data/normalizeResults/json_sortedLists_spec1.4.json
- tests/_data/normalizeResults/json_sortedLists_spec1.5.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.5.json
- tests/_data/serializeResults/json_complex_spec1.2.json.bin
- tests/_data/serializeResults/json_complex_spec1.3.json.bin
- tests/_data/serializeResults/json_complex_spec1.4.json.bin
- tests/_data/serializeResults/json_complex_spec1.5.json.bin
- tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.5.xml.bin
fixes https://github.com/CycloneDX/cyclonedx-javascript-library/issues/984
> feat: add `ExternalReferences[].hashes`

- CONTRIBUTING.md
- HISTORY.md
- src/models/metadata.ts
- src/serialize/json/normalize.ts
- src/serialize/json/types.ts
- src/serialize/xml/normalize.ts
- src/spec/_protocol.ts
- src/spec/consts.ts
- tests/README.md
- tests/_data/models.js
- tests/_data/normalizeResults/json_sortedLists_spec1.3.json
- tests/_data/normalizeResults/json_sortedLists_spec1.4.json
- tests/_data/normalizeResults/json_sortedLists_spec1.5.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
- tests/_data/normalizeResults/xml_sortedLists_spec1.5.json
- tests/_data/serializeResults/json_complex_spec1.3.json.bin
- tests/_data/serializeResults/json_complex_spec1.4.json.bin
- tests/_data/serializeResults/json_complex_spec1.5.json.bin
- tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
- tests/_data/serializeResults/xml_complex_spec1.5.xml.bin
See https://github.com/CycloneDX/cyclonedx-javascript-library/issues/1019 based on https://github.com/CycloneDX/cyclonedx-node-yarn/discussions/14#discussioncomment-8561774
> feat: `Metadata.licenses` & `Metadata.properties`

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
supersedes #1004
supersedes #1003
> ci: modernize artifact action

- .github/workflows/nodejs.yml
- HISTORY.md
- src/validation/xmlValidator.node.ts
- tests/integration/Validation.XmlValidator.test.js
prevent the XmlValidation from XXE parsing - prevent XML external entity (XXE) injection
This is considered a security measure. 
fixes #1061 as described here: https://github.com/CycloneDX/cyclonedx-javascript-library/pull/1063#issuecomment-2098335774
> feat:  XML Validator prevent parsing XXE

- HISTORY.md
- src/validation/xmlValidator.node.ts
- tests/_data/xxe_flag.txt
- tests/integration/Validation.XmlValidator.test.js
* The provided XML validation capabilities are hardened (via [#1064]; concerns [#1061])  
This is considered a security measure concerning XML external entity (XXE) injection.
[#1061]: https://github.com/CycloneDX/cyclonedx-javascript-library/issues/1061
[#1064]: https://github.com/CycloneDX/cyclonedx-javascript-library/pull/1064
----
This is not an actual change. 
Per default, the XML validation capabilities were already secure in the intended ways.
This is to prevent the fuckup like in the yanked v6.7.0
> refactor: XML validator explicitely harden against XXE injections

- HISTORY.md
- src/factories/packageUrl.ts
* Added `Factories.PackageUrlFactory`'s generic type's default back in
> fix: `PackageUrlFactory` generic default

- HISTORY.md
- src/_helpers/packageJson.ts
- src/builders/fromNodePackageJson.node.ts
- src/factories/fromNodePackageJson.node.ts
- src/types/index.ts
- src/types/nodePackageJson.ts
- src/types/packageJson.ts
* Public export `types.NodePackageJson`, which is the input type for various factories and builders 
this enables type checking downstream, like 
- `const foo: NodePackageJson = {...}`
- `const foo = {...} satisfies NodePackageJson`
> feat: public export of type `NodePackageJson`
