.github/workflows/nodejs.yml

bring CI/CT for windows nd macos

---

tests/integration/JsonNormalize.test.js
tests/integration/JsonSerialize.test.js
tests/integration/XmlNormalize.test.js
tests/integration/XmlSerialize.test.js

in reaction to test https://github.com/CycloneDX/cyclonedx-javascript-library/runs/6802978908?check_suite_focus=true
that failes because of a timeout ...

test: enlargen timeframe for complex integration tests

---

.npmignore
HISTORY.md

part of #75
texts are taken from the README

initial history

---

HISTORY.md
package.json

Widened the range of requirement `packageurl-js` to `0.0.6 - 0.0.7`

---

HISTORY.md
src/serialize/json/normalize.ts
tests/_data/models.js

fix: omitting version #137

---

HISTORY.md
src/serialize/xml/types.ts
tests/integration/Serialize.XmlNormalize.test.js

impove detection of XML's `anyURI` violations

---

HISTORY.md
package-lock.json
package.json

chore: use TypeScript 4.8 & bump dependencies

---

HISTORY.md
package-lock.json
package.json

see https://github.com/package-url/packageurl-js/issues/35
version tester: https://semver.npmjs.com/

feat: support `packageurl-js@^1`

---

HISTORY.md
src/_helpers/packageJson.ts
src/builders/fromNodePackageJson.node.ts
tests/integration/Builders.FromNodePackageJson.ComponentBuilder.test.js
tests/unit/Builders.FromNodePackageJson.ComponentBuilder.spec.js

deprecated `licenses` detection from `package.json`

---

HISTORY.md
README.md

caused by https://github.com/badges/shields/issues/8671

docs: fix GH-Wowkflow shields

---

tsconfig.node.json
tsconfig.web.json

chore: configure typescript `moduleSuffixes` 

---

src/resources.node.ts
src/spec.ts
tests/functional/Resources.node.spec.js

use TypeScript's simplification types over manual notations.

style: simplify record types

---

HISTORY.md
src/_helpers/packageJson.ts
src/builders/fromNodePackageJson.node.ts
src/factories/fromNodePackageJson.node.ts

docs: note to packageJson-like structure normalization

---

.github/workflows/nodejs.yml
examples/node-typescript/package.json
examples/node-typescript/tsconfig.json

TypeScript v5 was released. 
Let's assure the compatibility of our lib with it.

CI: asure TS5 compatibility

---

HISTORY.md
src/_helpers/packageJson.ts
tests/integration/Builders.FromNodePackageJson.ComponentBuilder.test.js

Package json split name group unorthodox names

---

HISTORY.md
src/serialize/json/normalize.ts
src/serialize/xml/normalize.ts
tests/_data/models.js
tests/_data/normalizeResults/json_sortedLists_spec1.2.json
tests/_data/normalizeResults/json_sortedLists_spec1.3.json
tests/_data/normalizeResults/json_sortedLists_spec1.4.json
tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
tests/_data/serializeResults/json_complex_spec1.2.json.bin
tests/_data/serializeResults/json_complex_spec1.3.json.bin
tests/_data/serializeResults/json_complex_spec1.4.json.bin
tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
tests/_data/serializeResults/xml_complex_spec1.4.xml.bin

fix: normalize expression over license

---

.github/workflows/nodejs.yml
.github/workflows/release.yml
examples/node-typescript/example.cjs/package.json
examples/node-typescript/example.mjs/package.json

node20 will be available soon -- 2023-04-18
see https://github.com/nodejs/release#release-schedule
lets test and run node20 in CI
fixes #651

ci: test node20

---

src/serialize/xml/normalize.ts

implement XML normalization according to https://github.com/CycloneDX/specification/issues/154

implement XML normalization according to CycloneDX/specification/issues/154

---

.eslintrc.js
package-lock.json
package.json

supersedes https://github.com/CycloneDX/cyclonedx-javascript-library/pull/878

chore(tools):  eslint standards

---

.github/dependabot.yml
package.json

see https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

chore: dependabot group

---

HISTORY.md
libs/universal-node-xml/index.js

Support XML serialization when running in bundles or non-standard

---

.github/workflows/nodejs.yml

node22 was released.
lets use it.

chore: test node22

---

HISTORY.md
res/schema/bom-1.2-strict.SNAPSHOT.schema.json
res/schema/bom-1.3-strict.SNAPSHOT.schema.json
res/schema/bom-1.4.SNAPSHOT.schema.json
res/schema/bom-1.5.SNAPSHOT.schema.json
tests/integration/Validation.JsonStrictValidator.test.js
tests/integration/Validation.JsonValidator.test.js
tools/schema-downloader/download.js

fixes https://github.com/CycloneDX/cyclonedx-javascript-library/issues/1059

fix: JsvonValidator allow arbitrary `$schema` 

---

package.json

chore: modernize `npm-run-all`

---

.github/workflows/release.yml
HISTORY.md
package.json

chore: publish package to `GithubPackages`

---

HISTORY.md
examples/node/javascript/example.cjs
src/_helpers/uri.ts
tests/_data/models.js
tests/_data/normalizeResults/json_sortedLists_spec1.2.json
tests/_data/normalizeResults/json_sortedLists_spec1.3.json
tests/_data/normalizeResults/json_sortedLists_spec1.4.json
tests/_data/normalizeResults/json_sortedLists_spec1.5.json
tests/_data/normalizeResults/json_sortedLists_spec1.6.json
tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
tests/_data/normalizeResults/xml_sortedLists_spec1.5.json
tests/_data/normalizeResults/xml_sortedLists_spec1.6.json
tests/_data/serializeResults/json_complex_spec1.2.json.bin
tests/_data/serializeResults/json_complex_spec1.3.json.bin
tests/_data/serializeResults/json_complex_spec1.4.json.bin
tests/_data/serializeResults/json_complex_spec1.5.json.bin
tests/_data/serializeResults/json_complex_spec1.6.json.bin
tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
tests/_data/serializeResults/xml_complex_spec1.5.xml.bin
tests/_data/serializeResults/xml_complex_spec1.6.xml.bin

fix: encode quotation mark in URLs

---

tools/code-style/package.json

this was not picked up by Dependabot. need to investigate

chore(dev-deps): bump CS tools

---

HISTORY.md
package.json

chore(deps): libxmljs2 0.35

---

.github/workflows/nodejs.yml

node24 was released - lets use it for tests.

ci: use node24
